name: Scan session
description: log session
title: "[SCAN] sub-xx_ses-yyy"
labels: [scan]
assignees: 
  - bpinsard
body:
- type: markdown
  attributes:
    value: "# general infos"

- type: checkboxes
  id: setup
  attributes:
    label: Setup
    description: check all the equipment that was set up
    options:
      - label: biopac
      - label: sensimetrics
      - label: eyetracker

- type: textarea
  attributes:
    label: general notes


- type: input
  attributes:
    label: run-01_task
    value: "## task-s06e0xy"
- type: checkboxes
  attributes:
    label: task-friends_run-01 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-friends_run-01 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-friends_run-01 notes

- type: input
  attributes:
    label: run-02_task
    value: "## task-s06e0xy"
- type: checkboxes
  attributes:
    label: task-friends_run-02 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-friends_run-02 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-friends_run-02 notes



- type: input
  attributes:
    label: run-03_task
    value: "## task-s06e0xy"
- type: checkboxes
  attributes:
    label: task-friends_run-03 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-friends_run-03 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-friends_run-03 notes

- type: input
  attributes:
    label: run-04_task
    value: "## task-s06e0xy"
- type: checkboxes
  attributes:
    label: task-friends_run-04 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-friends_run-04 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-friends_run-04 notes

